openapi: 3.1.0
info:
  version: 1.0.0
  title: Water Tracker
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    Water API
tags:
  - name: Water
    description: Water operations.
  - name: Auth
    description: Auth operations.
servers:
  # - url: http://localhost:3000
  - url: https://water-app-back-1n3p.onrender.com
paths:
  /api/auth/signup:
    post:
      $ref: ../src/swagger/paths/auth/signup/post.yaml
  /api/auth/signin:
    post:
      $ref: ../src/swagger/paths/auth/signin/post.yaml
  /api/auth/refresh:
    post:
      $ref: ../src/swagger/paths/auth/refresh/post.yaml
  /api/auth/logout:
    post:
      $ref: ../src/swagger/paths/auth/logout/post.yaml
  /api/users/current:
    get:
      $ref: ../src/swagger/paths/users/get.yaml
  /api/users:
     patch:
      $ref: ../src/swagger/paths/users/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
